# Generated by Django 4.1.11 on 2023-09-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_event_group_groupevent_remove_usergroup_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.userprofile'),
        ),
    ]
